#!/bin/sh

: ${GITHUB_USERNAME:=hortonworks}
: ${GITHUB_PROJECT:=cloudbreak-deployer}

main() {
    local os=$(uname -s)
    local latest_version=$(curl "https://raw.githubusercontent.com/hortonworks/cloudbreak-deployer/master/VERSION")
    local latest_tag=$(curl "http://release.infra.cloudera.com/hwre-api/listbuilds?stack=CB&release=${latest_version}&type=dev" | jq -r '.latest_build_version')
    local url=$(echo "https://public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_${latest_tag}_${os}_x86_64.tgz")

    local dest=/usr/bin
    hash -r > /dev/null
    if (command -v cbd > /dev/null); then
        local existing=$(command -v cbd)
        dest=${existing%/*}
    else
        if echo "$PATH" | grep -q '/usr/local/bin' ; then
           dest=/usr/local/bin
        fi
    fi

    curl -Ls $url | tar -xz -C ${dest}
    echo "---> cbd installed into ${dest}"
}

main "$@"
