#!/bin/sh

: ${GITHUB_USERNAME:=hortonworks}
: ${GITHUB_PROJECT:=cloudbreak-deployer}

main() {
    declare branch=${1:-master}

    local os=$(uname -s)
    local url=$(echo "https://public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_snapshot_${os}_x86_64.tgz")

    local dest=/usr/bin
    hash -r > /dev/null
    if (command -v cbd > /dev/null); then
        local existing=$(command -v cbd)
        dest=${existing%/*}
    else
        if echo "$PATH" | grep -q '/usr/local/bin' ; then
           dest=/usr/local/bin
        fi
    fi

    curl -Ls $url | tar -xz -C ${dest}
    echo "---> cbd installed into ${dest}"
}

main "$@"
